### ISSUE TITLE
feature request: semantic or regexp-able word dictionary

### ISSUE THREAD

**Issue by nekomeowww** [LittleSound/interline-translate#19]
## Background

In many languages, APIs from standard librarie may have their own meaning instead of directly translated ones. For example, in Golang:

```go
stat, err := os.Stat(filePath)
```

Doesn't mean *statistics*, but rather the file system inode status. Same patterns extend to Node.js, Python as well.

When using machines and APIs to translate, context is crutial. Short words are fairly short and has higher appearing frequency, but the downsides are caused by short context to, while words like `chmod`, `cwd`, `symlink` is short and quite easy to learn and exists only for OS field, what about `tokens`, `roundTripper`, `conn` words that can have so many meaning across different context over different fields?

## Proposal

What if we could some how to expose users to create their own dictionaries for **special technology terms** and publish them as dedicated npm packages so that this plugin can integrate with to build larger community.

One interesting product or feature that has similar *special terms dictionaries* is *Lingo* from Feishu (Lark): https://www.feishu.cn/product/lingo .

Lingo allows users to creator and manage their own dictionaries and knowledge base links for terms, no matter a code name of a product that only internal teams can understand, or some ambiguous words that often mixed by developers.

For simple implementation, can we have a new feature to customize our own RegExp pairs to manully translate the words instead of automatically?

## Proposed Implementation / Workflow

- User find one machine translated word ambiguous or horribly wrong.
- User opens up the command palette to add one pair of RegExp with translation.
- Plugin prompt user to input the desired filename matching RegExp
- Plugin prompt user to input the desired code pattern matching RegExp
- Plugin prompt user to input the desired translate text.

Which can be stored like this:

```json
{
  "intelliDictionary": [
    {
      "type": "regexp",
      "filenameRegExp": ".*\.go",
      "patternRegExp": "^(.*), (_|err) :?= (os\.Stat)\(.*\)$",
      "translation": [
        { "group": "$1", text: "状态" },
        { "group": "$2", text: "错误" },
        { "group": "$3", text: "获取文件状态" },
      ]
    }
  ]
}
```

<img width="1777" alt="image" src="https://github.com/user-attachments/assets/7aab7cd4-31e5-4c75-a2fc-a8894847742f">

I am not sure how TextMate and token parser works in VSCode, if we can process the file content line by line, perhaps we could generate a corresponding translation map for the matched positions, text values and directly replace the result with desired values.

## Further reading

For *semantic* support, I was wondering, is it possible to parse the pased AST and then feed the import statement into dictionary for translation, so we can extend to translate a entire line of code with templates instead of separated words.

For example, in Golang with Kubernetes API, we usually write:

and use it as

```go
client.CoreV1().Pods(flags.GetNamespace()).Get(cmd.Context(), podName, metav1.GetOptions{})
```

This line is basically stating:

```
use core/v1 API to fetch Pods with $2 in $1 namespace, options are $3
```

with the following config:

```json
{
  "intelliDictionary": [
    {
      "type": "regexp",
      "filenameRegExp": ".*\.go",
      "patternRegExp": "^client\.(CoreV1)\(\).Pods\((.*)\).Get\((.*),(.*), (.*)\)$",
      "translationTemplate": {
        "content": "用 $1 API 获取在 $2 中名为 $4 的 Pod，参数为 $5"
      },
      when: {
        "languageServer": "golang", // can be extended with npm packages as plugins
        "seekPattern": "(client)\.CoreV1\(\).Pods\((.*)\).Get\((.*),(.*), (.*)\)",
        "seekGroup": "$1",
        "asType": "k8s.io/client-go/kubernetes.Interface"
      }
    }
  ]
}
```

<img width="1765" alt="image" src="https://github.com/user-attachments/assets/cb3cde1f-83ea-48ba-89ca-4f4f0741bea3">

where the parsed AST token with types from Language Servers could tell us whether this `client` is actually a `kubernetes.Interface` type. And intepretate

**Comment by LittleSound** [comment]
The existing architecture basically cannot achieve this function and requires a lot of refactoring.

Moreover, I feel that this deviates somewhat from the positioning of interline translate. For such needs as explaining what a piece of code is doing, I generally use AI.

However, this is indeed a very interesting idea, thank you.
